# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC

# Development mode overrides
services:
  tt_studio_backend:
    volumes:
      # Mount the local api directory for live code changes
      - ./backend:/backend
    command: python ./manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True

  tt_studio_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    
    ports:
      - "3000:3000"
    
    environment:
      - VITE_ENABLE_DEPLOYED
      - VITE_APP_TITLE
      - VITE_ENABLE_RAG_ADMIN
      - VITE_TEST_AUDIO_URL
      - VITE_TEST_AUDIO_AUTH
      - VITE_LOGIN_USERNAME
      - VITE_LOGIN_PASSWORD
      - VITE_LLAMA_AUTH_TOKEN
      - VITE_SPECIAL_API_URL
      - VITE_API_HOST
      - VITE_STABILITY_API_KEY

    volumes:
      - ./frontend:/app
      - /app/node_modules